### ISSUE TITLE
Сортировка вкладки "Избранное" по алфавиту

### ISSUE THREAD

**Issue by Username1-a** [RadiationX/ForPDA#11]
Если будет возможность, добавьте пожалуйста возможность сортировки избранного по алфавиту, а не по последней активной теме

Так было бы удобнее найти в этом списке нужную тему, а то пишут во многих темах очень часто и порядок их в Избранном постоянно меняется 
(К тому же, какая по большому счёту польза от осознания того, что кто-то опять написал в активной теме на несколько десятков человек)

**Comment by RadiationX** [comment]
Так эта функция есть, там прям на экране избранного можно настроить сортировку

**Comment by Username1-a** [comment]
> Так эта функция есть, там прям на экране избранного можно настроить сортировку

Точно, прошу прощения, спасибо
