### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by Edfgdz** [RadiationX/ForPDA#3]
Hi,will you add English translation to this app?

**Comment by Edfgdz** [comment]
Sorry,i am not a english user,after switch system language to english,i find having add english language.

**Comment by iSanechek** [comment]
Hey. You can switch to english in settings without switching in system.

**Comment by Edfgdz** [comment]
I got language switch setting in english system ,but after switch to english,some texts in app still not be translated.Wish continue translate those texts.

**Comment by Edfgdz** [comment]
Can you make this app directly display English language when it is firstly opened when user phone system default language isnt Russisn,this can reduce users confusion.

**Comment by slartus** [comment]
No it's russian forum.

**Comment by iSanechek** [comment]
in plans to add a translation with google translator, but the translation is so-so.
Many people write with mistakes and with Russian slang.

**Comment by Edfgdz** [comment]
I mean the text owned by app itself,like DevDB,News in left sidebar,but it is better if you add g translator for content by 4pda forum.
At present , i usually share to g translator app.
