### ISSUE TITLE
Белый splash screen при запуске ForPDA на тёмной теме

### ISSUE THREAD

**Issue by Username1-a** [RadiationX/ForPDA#4]
Здравствуйте.
Было бы неплохо сделать тёмный splash screen на тёмной теме при запуске приложения, а то сейчас он белый.

Версия 0.9.0

**Comment by RadiationX** [comment]
Это невозможно исправить. На момент запуска приложения, нет возможности указать нужный цвет фона. По умолчанию берётся белый фон.

**Comment by slartus** [comment]
возможно. через splash screen

**Comment by RadiationX** [comment]
@slartus невозможно повлиять на цвет в windowBackground до его отображения.

**Comment by slartus** [comment]
через стиль

**Comment by RadiationX** [comment]
@slartus не получится. в тот момент невозможно получить настройки темы

**Comment by slartus** [comment]
@RadiationX  что не получится? сделать черный фон splashscreen при запуске?

**Comment by slartus** [comment]
> Версия 0.9.0

что это за версия вообще

**Comment by TheGreySquare** [comment]
Спасибо за ответ.

Надеюсь вы придёте к единому мнению

**Comment by RadiationX** [comment]
@slartus сделать зависимость от выбранной темы в приложении. а не черный цвет

**Comment by RadiationX** [comment]
Исправлено в последних версиях приложения. Работает только начиная с 10 андроида - ограничение системы
